### PR TITLE
Fixes HTTPS and the build process.

### PR DESCRIPTION
**Pull request by hinnerk**
* Adds `X-Forwarded-Proto` for requests that came in over HTTPS.
* Removes glide.lock so that changes to the `proxy` submodule actually get build.

### CODE REVIEW

**Comment by tiff** [comment]
LGTM. Feel free to merge it yourself once tests passed

**Comment by colszowka** [comment]
@hinnerk Is it correct to remove the gilde.lock? I gather this is similar to what ruby's bundler does with `Gemfile.lock`, in that it locks in your dependencies at specific, known-to-work versions. Without this, you do not know what gets installed as your dependencies and hence are setting yourself up for terrible dependency hell issues.

**Comment by colszowka** [comment]
Also, what is this needed for? Can we add a PT link please? And a unit test might make sense ;)

**Comment by colszowka** [comment]
Ok, found the story I think: https://www.pivotaltracker.com/story/show/136685751

**Comment by hinnerk** [comment]
Please read the description in order to see that removing `glide.lock` was not only intentional but even necessary. @colszowka ;)

**Comment by colszowka** [comment]
@hinnerk But shouldn't bumping dependency versions be a manual step exactly for that reason? If I do a rebuild of a branched old version of this code, I want to use the old version of the dependency, too.

**Comment by hinnerk** [comment]
The problem is that glide vendors something that's part of the same repository. Maybe a bug in glide? What do you think @kdomanski ?

**Pull request merged**
